starkware-libs/starkgate-frontend

src/abis/ethereum/index.js
src/abis/starknet/index.js
src/hooks/useContract.js
src/hooks/useTokenBalance.js
src/providers/TokensProvider/TokensProvider.js

`export * as someModule from './module.json` exported the file as `Module` instead of `Array`, which cause contract initialization to fail.

fix: app crashes on production build

---

.eslintrc.json
package.json
src/__tests__/utils/hash.spec.js
src/abis/l1/StarknetMessaging.json
src/constants.js
src/enums/TransactionHashPrefix.js
src/enums/index.js
src/hooks/useEventListener.js
src/utils/hash.js
yarn.lock

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/66)

feat: add nonce to txHash calculation

---

src/__tests__/utils/object.spec.js
src/components/Features/Account/Account.js
src/components/Features/Bridge/Bridge.hooks.js
src/components/Features/Bridge/Bridge.js
src/components/Features/Bridge/Bridge.slice.js
src/components/Features/ToastProvider/ToastProvider.js
src/components/Features/TransferLog/TransferLog.module.scss
src/components/UI/Toast/CompleteTransferToL1Toast/CompleteTransferToL1Toast.js
src/components/UI/Toast/ToastFooter/ToastFooter.js
src/components/UI/Toast/ToastFooter/ToastFooter.module.scss
src/components/UI/Toast/ToastFooter/ToastFooter.strings.js
src/components/UI/Toast/ToastHeader/ToastHeader.module.scss
src/components/UI/Toast/TransferToast/TransferToast.js
src/components/UI/TransferLogContainer/TransferLogContainer.js
src/config/strings.json
src/styles/colors.module.scss
src/utils/object.js
yarn.lock

enhancement:
Added to the toasts link to transfer-log. onClick switches to L1 or L2, and opens the account menu with the log expanded. Added 'menuProps' to Bridge.js, currently used only by the account menu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/76)

feat(toasts): add link to transfer log

---

src/components/Features/Account/Account.js
src/components/Features/SelectToken/SelectToken.js

Calling the function 'showTransferMenu' from clicking on the 'Account.js' + 'SelectToken.js' > backButton was accidentally passing the click-event.
This PR fixes that. Now it's clear that all calls to the function 'showTransferMenu' don't pass the browser event.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/89)

fix: redux error on switching menu "non-serializable value was detected"

---

src/components/Features/ToastProvider/ToastProvider.js

Remove the call to show the toast: "Waiting for transaction to be accepted on L2..."
Keep all related code written, because soon we might want to re-display it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/92)

fix: remove pending transfer toast

---

src/components/Containers/Header/Header.js
src/components/Containers/Header/Header.module.scss
src/components/Containers/Header/Header.strings.js
src/components/UI/Tab/Tab.js
src/components/UI/Tab/Tab.module.scss
src/components/UI/WalletButton/WalletButton.module.scss
src/components/UI/index.js
src/config/constants.js
src/config/strings.js
src/utils/browser.js

Add a new Tab component, use it in Header with link to StarkNet channel on discord.
Edit _utils.browser.openInNewTab_ to accept argument 'target' -
Specify it for the discord link, so it focuses on that tab if already opened before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/104)

feat: add discord tab

---

src/components/Containers/Header/Header.js
src/components/Containers/Header/Header.module.scss
src/components/UI/Button/Button.module.scss
src/components/UI/Tab/Tab.js
src/components/UI/Tab/Tab.module.scss
src/components/UI/WalletButton/WalletButton.js
src/components/UI/WalletButton/WalletButton.module.scss
src/styles/colors.module.scss

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/118)

fix: tab UX

---

CHANGELOG.md
src/components/Features/Transfer/Transfer.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/134)

fix: when clicking Max button on L2 network 0 is shown instead of max balance

---

CHANGELOG.md
src/__tests__/utils/number.spec.js
src/components/Features/Transfer/Transfer.js
src/components/Features/Transfer/Transfer.strings.js
src/config/strings.js
src/utils/index.js
src/utils/number.js

* A fix for invalidation of negative amounts
* A fix for invalidation of too many decimals points
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/135)

fix: invalidation of negative amounts and too many decimal points

---

src/config/envs.js
src/providers/WalletsProvider/WalletsProvider.js

fix the condition envs.js > autoConnect represents, to reflect properly the settings in the env;
Add try-catch in connectL2Wallet, since in the scenario of ArgentX not installed- the enable function throws.
With these fixes, when in the current environment defined auto-connect = false, if ArgentX isn't installed in the browser-
The 'prompt install' modal is displayed, and the error of 'no starknet found in window' is caught.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/153)

fix: app crashed when trying to connect while ArgentX wasn't installed

---

src/routes/Terms/Terms.js

Solution: check for `scrollTop + clientHeight >= scrollHeight` and round-up the result instead of `scrollTop + clientHeight === scrollHeight`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/155)

fix: accept button stays disabled when zoom is different from 100%

---

src/config/faqs.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/157)

fix(Faq): question 8

---

src/components/UI/Modal/Modal/Modal.js
src/components/UI/Modal/ModalBody/ModalBody.module.scss
src/components/UI/Modal/ModalText/ModalText.module.scss

Set also a max-width and an 'overflow-wrap' so modal-content that has very long strings (like in some error messages) will wrap correctly. Yet, keep the centered style for short content.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/161)

fix: bad overflow in modal for content with very long strings

---

src/components/UI/Button/Button.js
src/components/UI/Button/Button.module.scss
src/enums/LoginErrorType.js
src/enums/WalletErrorType.js
src/enums/index.js
src/hooks/useTransferToL1.js
src/providers/AppProvider/app-hooks.js
src/providers/EventManagerProvider/event-manager-hooks.js
src/providers/WalletsProvider/WalletsProvider.js
src/providers/WalletsProvider/wallets-hooks.js
src/routes/Login/Login.js

Add `useStarknetWallet` hook in which I expose the same API as `useWallet` and manage all the chain-related logic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/168)

feat: validate starknet wallet chain ID

---

src/components/UI/Modal/TransactionSubmittedModal/TransactionSubmittedModal.js
src/hooks/useTransferToL1.js
src/hooks/useTransferToL2.js
src/index.js
src/providers/EventManagerProvider/event-manager-hooks.js
src/providers/TransfersLogProvider/TransfersLogProvider.js
src/providers/WalletsProvider/WalletsProvider.js
src/providers/index.js
src/routes/Bridge/Bridge.js

Do not enforce the modal to stay on screen if you have not been able to calculate the L2 hash (the transaction itself has already been sent). Keep doing it in the background when iterating the transfers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/169)

fix: calc L2 tx hash in the background

---

src/providers/BlockHashProvider/BlockHashProvider.js
src/providers/TransfersLogProvider/TransfersLogProvider.js
src/utils/blockchain/starknet.js

`defaultProvider` by default is working against Goerli testnet. 
For mainnet envs we should work with the wallet provider (i.e. `getStarknet().provider`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/170)

fix: use wallet provider for all provider calls

---

src/components/UI/MaxButton/MaxButton.module.scss
src/components/UI/TokenInput/TokenInput.js

Temporary disable the max button until estimateGas logic will be added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/173)

fix: temporary disable max button

---

src/__tests__/utils/wallet.spec.js
src/utils/wallet.js

Issue: when the balance is zero with more than 5 digits after the dot (i.e. 0.0000001) balance is shown as 0.
Solution: transform the displayed balances to strings and format their display to `0.00000...` in such cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/172)

fix: cancel toFixed when format balances

---

src/components/Features/Transfer/Transfer.js
src/config/strings.js

Update text to:
"You have exceeded the maximum transfer amount ( {The max amount} {token symbol}). Please reduce the amount  and try again."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/174)

fix: update text for the attempt to deposit more than the allowable amount

---

src/libs/starknet.js
src/providers/WalletsProvider/wallets-hooks.js

Issue:
In case the user selected a wallet but the wallet is locked or the dapp is not connected (i.e. not yet authorized), the promise will not be resolved. so I don't have a way to differentiate between the selection of the wallet and the actual connection to the wallet
Solution: 
Use `connect` API from `get-starknet-wallet` which returns the actual selected wallet from the list 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/175)

fix: connection modal overrides gsw selection modal

---

src/components/Features/ToastProvider/ToastProvider.js

Dismiss programmatically if the `l1hash` prop exists on `transfer` object and this toast is rendered before the re-render. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/179)

fix: CompleteTransferToL1 toast remains on display after tx is done

---

src/components/UI/Modal/ModalText/ModalText.module.scss
src/hooks/useTransferProgress.js

Fix deprecated reference to JSON in `strings.js`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/194)

fix: modal error messages not displayed

---

src/hooks/index.js
src/hooks/useAccountChange.js
src/providers/EventManagerProvider/EventManagerProvider.js
src/providers/TokensProvider/TokensProvider.js
src/providers/index.js

Move `EventManagerProvider` to app-level to avoid re-rendering when visiting non-bridge pages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/197)

fix: move EventManagerProvider to app-level

---

src/App.js
src/components/UI/BurgerMenu/BurgerMenu.js
src/components/UI/BurgerMenu/BurgerMenu.module.scss
src/components/UI/Menu/Menu.module.scss
src/components/UI/MultiChoiceMenu/MultiChoiceMenu.js
src/components/UI/SideButton/SideButton.js
src/components/UI/SideButton/SideButton.module.scss
src/hooks/index.js
src/hooks/useVars.js
src/providers/AppProvider/AppProvider.js
src/providers/AppProvider/app-context.js
src/routes/Liquidity/Liquidity.js
src/styles/variables.module.scss

When routing to scrolling pages handle Discord button so it won't overlay the scrollbar. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/205)

fix: handle Discord button on scroll

---

package.json
src/__tests__/utils/parser.spec.js
src/__tests__/utils/wallet.spec.js
src/components/Features/Transfer/Transfer.js
src/hooks/useIsMaxTotalBalanceExceeded.js
src/hooks/useTransferToL2.js
src/utils/parser.js
src/utils/wallet.js
yarn.lock

Used the unit map of `web3` to do the conversions.
The problem is that in this map the jumps are in 3 decimals, I.e. 3,6,9,12,18...
So if we have a token with 8 decimals, for example, we didn't convert him correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/228)

fix(2918898444): Too many zeros shows for WBTC

---

src/providers/WalletsProvider/wallets-hooks.js

This fix is for a scenario where the user closes the popup window of the wallet connection and goes into the main application screen. the solution is to add another check in the if statement which checks that the address that we receiving from the `get-starknet` library is something not falsy (in our case is an empty string)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/232)

fix(2878552430): User routes to the main screen even if not choose an L2 wallet

---

.env
src/config/constants.js
src/enums/ChainType.js

move `APP_URL_GOERLI` and `APP_URL_MAINNET` from .env to constants.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/247)

chore: move app urls to constants.js

---

src/components/UI/NetworkWalletButton/NetworkWalletButton.js

Call wallet connect handler while wallet status is `WalletStatus.ERROR`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/268)

fix(3080263579): While error is raised when connecting to the wallet, modal isn't shown again

---

src/components/UI/Modal/LoginModal/LoginModal.js
src/components/UI/Modal/ModalWrapper.js

Needed to add `else` statement since now we're always calling `connectWallet(...)` from the `LoginModal` comp.
Solves #[3094709997](https://starkware.monday.com/boards/2847524005/pulses/3094709997)
---
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/275)

fix(3094709997): when clicking connect starknet wallet, gsw message pops up (opera)

---

src/components/UI/SideButton/SideButton.module.scss

Remove `border` CSS from `SideButton` component.
Solves #[3155991918](https://starkware.monday.com/boards/2847524005/pulses/3155991918)
---
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/295)

fix(3155991918): redundant purple border on Discord button
