src/config/addresses/tokens/tokens.ethereum.js, src/config/addresses/tokens/tokens.starknet.js, src/enums/NetworkType.js, src/providers/TokensProvider/tokens-reducer.js
Fixed https://github.com/starkware-libs/starknet-bridge/issues/13
=> fix: change ethereum token name

src/components/Features/Transfer/Transfer.js
Fixed https://github.com/starkware-libs/starknet-bridge/issues/36
=> fix: max amount in withdrawal causes an error

src/components/Features/TransferLog/TransferLog.js, src/components/UI/LinkButton/LinkButton.js, src/components/UI/LinkButton/LinkButton.module.scss, src/enums/TransactionStatus.js
Fixed https://github.com/starkware-libs/starknet-bridge/issues/34
=> fix: show txs links before ACCEPTED_ON_L1

src/components/Containers/Header/Header.js, src/components/Containers/Header/Header.module.scss
Fixed https://github.com/starkware-libs/starknet-bridge/issues/23
=> fix: logo is not clickable

src/api/bridge.js, src/components/Features/ModalProvider/ModalProvider.hooks.js, src/components/UI/Modal/TransactionSubmittedModal/TransactionSubmittedModal.js, src/components/UI/Modal/TransactionSubmittedModal/TransactionSubmittedModal.strings.js, src/components/UI/Toast/ToastHeader/ToastHeader.module.scss, src/config/strings.json, src/hooks/useTransfer.js, src/utils/contract.js
=> fix: transfer from starknet modal progress

.eslintrc.json, src/components/Features/Account/Account.js, src/components/Features/ModalProvider/ModalProvider.hooks.js, src/components/Features/ToastProvider/ToastProvider.js, src/components/Features/Transfer/Transfer.js, src/components/UI/Modal/TransactionSubmittedModal/TransactionSubmittedModal.js, src/hooks/index.js, src/hooks/useEventListener.js, src/hooks/useTransfer.js, src/hooks/useTransferProgress.js, src/utils/contract.js
=> refactor: useTransfer hooks

src/components/UI/Modal/TransactionSubmittedModal/TransactionSubmittedModal.js, src/providers/BlockHashProvider/BlockHashProvider.js
=> chore: fix lints

README.md, package.json, public/index.html
=> chore: update package name

src/components/Features/TransferLog/TransferLog.js, src/enums/TransactionStatus.js
=> fix: tx status friendly message

.github/workflows/push.yml, .github/workflows/tag.yml, .versionrc.json, package.json, scripts/npm-publish.bash
=> chore: add [skip ci] to release commit

src/hooks/useContract.js
=> feat: cache contracts

src/components/Features/ToastProvider/ToastProvider.js, src/components/Features/ToastProvider/ToastProvider.strings.js, src/config/strings.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/68)
=> feat: alpha disclaimer

.eslintrc.json, src/__tests__/services/storage-manager.spec.js, src/__tests__/utils/hash.spec.js, src/services/storage-manager.js, src/utils/hash.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/67)
=> feat(local storage): hash transfers

src/config/addresses/tokens/tokens.l1.js, src/config/addresses/tokens/tokens.l2.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/70)
=> chore: update USDC addresses

src/components/Features/Transfer/Transfer.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/72)
=> fix: max balance error

src/components/Features/Account/Account.js, src/components/Features/Transfer/Transfer.selectors.js, src/components/Features/Transfer/Transfer.slice.js, src/components/Features/TransferLog/TransferLog.js, src/components/Features/TransferLog/TransferLog.strings.js, src/components/UI/Modal/TransactionSubmittedModal/TransactionSubmittedModal.js, src/components/UI/Modal/TransactionSubmittedModal/TransactionSubmittedModal.strings.js, src/config/strings.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/73)
=> chore: renaming withdraw/deposit to transferToL1/transferToL2

.github/workflows/push.yml, .versionrc.json, package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/75)
=> chore: change commit message for prereleases

src/config/addresses/tokens/tokens.l1.js, src/config/addresses/tokens/tokens.l2.js, yarn.lock
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/77)
=> fix: remove MIM and FRAX tokens

src/config/addresses/tokens/tokens.l1.js, src/config/addresses/tokens/tokens.l2.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/84)
=> fix: update ETH token addresses and add SLF token

.github/workflows/pull_request.yml, .github/workflows/push.yml, .github/workflows/tag.yml, .npmrc, package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/83)
=> chore: force node version

src/config/tokens.js
Updated addreses of the DAI bridge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/100)
=> chore(DAI v2): update DAI token addresses

src/components/Features/ToastProvider/ToastProvider.js, src/enums/ToastType.js, src/enums/index.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/114)
=> fix: toasts rendered multiple times

src/config/constants.js, src/providers/TokensProvider/TokensProvider.js, src/providers/TokensProvider/tokens-reducer.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/115)
=> feat: retry mechanism to fetch balance

src/analytics/track.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/127)
=> fix: empty callback in promise .then

CHANGELOG.md, src/components/Features/Transfer/Transfer.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/131)
=> fix: after clicking max button on L2 it shows "0"

src/abis/l1/StarknetERC20Bridge.json, src/abis/l1/StarknetEthBridge.json, src/hooks/useTransferToL1.js, src/hooks/useTransferToL2.js, src/providers/EventManagerProvider/EventManagerProvider.js, src/providers/EventManagerProvider/event-manager-context.js, src/providers/EventManagerProvider/event-manager-hooks.js
* Update bridges ABI - now filter fields are indexed and can be used for filtering events.
* Simplify implementation in the `EventManagerProvider`.
* Remove listener of `LogMessageToL2` event - now after `LogDeposit` event dispatched we're fetching past `LogMessageToL2` events and finding the proper event.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/139)
=> fix: new event driven implementation for deposit and withdraw

src/config/faqs.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/147)
=> chore: add faq

src/config/strings.js, src/routes/Terms/Terms.js, src/routes/Terms/Terms.module.scss, src/routes/Terms/Terms.strings.js
Add terms-notes text to the Terms tab.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/144)
=> fix(Terms): add notes

src/routes/Terms/Terms.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/158)
=> fix: accept button stayed disabled when browser zoom is different from 100%

src/components/Containers/Footer/Footer.js, src/components/Containers/Header/Header.js, src/components/Features/Account/Account.js, src/components/Features/SelectToken/SelectToken.js, src/components/Features/ToastProvider/ToastProvider.js, src/components/Features/Transfer/Transfer.js, src/components/Features/TransferLog/TransferLog.js, src/components/UI/AccountAddress/AccountAddress.js, src/components/UI/LogoutButton/LogoutButton.js, src/components/UI/MaxButton/MaxButton.js, src/components/UI/Modal/OnboardingModal/OnboardingModal.js, src/components/UI/Modal/TransactionSubmittedModal/TransactionSubmittedModal.js, src/components/UI/NetworkMenu/NetworkMenu.js, src/components/UI/SearchToken/SearchToken.js, src/components/UI/Toast/CompleteTransferToL1Toast/CompleteTransferToL1Toast.js, src/components/UI/Toast/ToastFooter/ToastFooter.js, src/components/UI/Toast/TransferToast/TransferToast.js, src/components/UI/TokenBalance/TokenBalance.js, src/components/UI/TokenInput/TokenInput.js, src/components/UI/TransferButton/TransferButton.js, src/components/UI/TransferLogContainer/TransferLogContainer.js, src/components/UI/WalletButton/WalletButton.js, src/hooks/useTransferProgress.js, src/hooks/useTranslation.js, src/providers/ModalProvider/modal-hooks.js, src/routes/Faq/Faq.js, src/routes/Login/Login.js, src/routes/Terms/Terms.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/162)
=> refactor: useTranslation hooks

src/config/tokens.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/167)
=> fix: add ETH mainnet addresses 

.github/workflows/gcr_push_workflow.yml, .github/workflows/push_frontend_images.yml
In case a patch version is tagged from a release tag run the workflow and push the image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/195)
=> ci: patch handling

.github/workflows/destroy_on_merge.yml, .github/workflows/helm_upgrade_workflow.yml, .github/workflows/pull_request.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/204)
=> ci: add --wait conditions to helm deployment

src/assets/svg/icons/minus-circle.svg, src/assets/svg/icons/plus-circle.svg, src/components/Features/Transfer/Transfer.js, src/components/UI/BurgerMenu/BurgerMenu.js, src/components/UI/BurgerMenuItem/BurgerMenuItem.js, src/components/UI/BurgerMenuItem/BurgerMenuItem.module.scss, src/components/UI/CollapseExpand/CollapseExpand.js, src/components/UI/FullScreenContainer/FullScreenContainer.js, src/components/UI/FullScreenContainer/FullScreenContainer.module.scss, src/components/UI/SideButton/SideButton.js, src/components/UI/TransferLogContainer/TransferLogContainer.js, src/config/constants.js, src/config/faqs.js, src/config/strings.js, src/routes/Faq/Faq.js, src/routes/Faq/Faq.module.scss, src/routes/Terms/Terms.module.scss
change documentation links on FAQ page + refactor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/206)
=> fix(GATE-2): change documentation links on FAQ page

src/App.js, src/config/tokens.js, src/providers/TokensProvider/TokensProvider.js, src/providers/TokensProvider/tokens-reducer.js
Assign indexes on the initial state and not on every filtering.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/208)
=> fix(GATE-9): incorrect DAI amount

src/api/bridge.js, src/api/erc20.js, src/hooks/useFetchData.js, src/hooks/useTransferToL2.js, src/providers/BlockHashProvider/BlockHashProvider.js, src/providers/TokensProvider/TokensProvider.js, src/providers/TransfersLogProvider/TransfersLogProvider.js, src/utils/ethereum.js, src/utils/index.js, src/utils/starknet.js
Use a promise handler to reduce the try/catch statements in the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/209)
=> refactor: promise handler instead of try/catch statement

src/hooks/useTransferToL1.js, src/hooks/useTransferToL2.js, src/providers/BlockHashProvider/BlockHashProvider.js, src/providers/TransfersLogProvider/TransfersLogProvider.js, src/utils/ethereum.js
Contract events are sometimes not dispatched - until this will be investigated and resolved, use promise as the indication for tx completed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/212)
=> fix(useTransferToL1/2): use promise instead of contract event

src/components/UI/Circle/Circle.module.scss, src/components/UI/Modal/Modal/Modal.module.scss, src/components/UI/Modal/ModalBody/ModalBody.module.scss, src/components/UI/Modal/ModalFooter/ModalFooter.js, src/components/UI/Modal/ModalFooter/ModalFooter.module.scss, src/components/UI/Modal/ModalHeader/ModalHeader.module.scss, src/components/UI/Modal/ModalMessage/ModalMessage.module.scss, src/components/UI/Modal/ModalMessage/RefreshMessage.js, src/components/UI/Modal/ModalMessage/TransferToL1Message.js, src/components/UI/Modal/ModalMessage/TransferToL2Message.js, src/components/UI/Modal/ModalText/ModalText.module.scss, src/components/UI/Modal/ModalTitle/ModalTitle.module.scss, src/components/UI/Modal/ModalWrapper.js, src/components/UI/Modal/ProgressModal/ProgressModal.js, src/components/UI/Modal/ProgressModal/ProgressModal.module.scss, src/components/UI/Modal/TransactionSubmittedModal/TransactionSubmittedModal.js, src/components/UI/Modal/TransactionSubmittedModal/TransactionSubmittedModal.module.scss, src/components/UI/Modal/TransactionSubmittedModal/TransactionSubmittedModalButton.js, src/components/UI/RefreshIcon/RefreshIcon.js, src/components/UI/Stepper/Stepper.module.scss, src/providers/ModalProvider/modal-hooks.js, src/providers/ModalProvider/modal-reducer.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/214)
=> feat: extend modal to receive components in footer and header

LICENSE
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/220)
=> chore: add LICENSE doc

src/config/tokens.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/225)
=> feat(2890247979): WBTC, USDT, USDC mainnet addresses

src/providers/WalletsProvider/WalletsProvider.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/226)
=> fix(2918791557): L2 tokens fetched before account is updated

.github/workflows/gcr_push_workflow.yml, release.config.js
push gcr image if `inputs.branch_name` starts with `refs/tags`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/242)
=> ci: create gcr image for pushing tag from local

src/config/constants.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/244)
=> fix(2991866013): Update to current Discord link

src/App.js, src/config/faqs.js
remove discord link from UI and faq
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/251)
=> fix: remove discord link

package.json, yarn.lock
Update starknet.js version to `3.19.0`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/246)
=> feat(2983084397): update starknet.js version

.github/PULL_REQUEST_TEMPLATE.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/270)
=> chore: update pr template instructions

src/components/UI/SourceSelect/SourceSelect.theme.js
* add selected icon to the selected menu option
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/293)
=> add selected icon

src/assets/svg/icons/selected.svg, src/components/UI/ChainSelect/ChainSelect.js, src/components/UI/ChainSelect/ChainSelect.module.scss, src/components/UI/ChainSelect/ChainSelect.theme.js, src/components/UI/SourceSelect/SourceSelect.theme.js, src/styles/colors.module.scss
Align the Chain Select to the Figma design
Solves #[3175163956](https://starkware.monday.com/boards/2891230138/pulses/3175163956)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/315)
=> fix(3175163956): align chain select to Figma design

.github/workflows/gcr_push_workflow.yml
Change github ci pipeline on master push
Solves #[INSERT_MONDAY_ID_HERE](INSERT_MONDAY_URL_HERE)
---
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkgate-frontend/322)
=> ci: on master push pipeline
